---
title: "descriptive"
author: "neele engelmann"
date: "2025-03-07"
output: html_document
---

```{r}
library(tidyverse)
```

descriptive

```{r}
p_prop <- rules_allstudies %>%
  filter(task=="rules" & study != "punishment") |> 
  mutate(response = ifelse(study=="comply" & response == 1,0,
                           ifelse(study=="comply" & response == 0,1,response))) |> 
  group_by(text, purpose, response) %>%
  summarise(count = n(), .groups = "drop") %>%
  group_by(text, purpose) %>%
  mutate(proportion = round(count / sum(count),2),
         se = sqrt((proportion*(1-proportion))/count),
         CI_lower = proportion - 1.96*se,
         CI_upper = proportion + 1.96*se) |> 
  mutate(condition = ifelse(text==1 & purpose==1,"full violation",
                            ifelse(text==0 & purpose ==0, "no violation",
                                   ifelse(text==1 & purpose==0, "text violation","purpose violation")))) |> 
  filter(response==1) |> 
  mutate(condition=factor(condition,levels=c("full violation","text violation","purpose violation","no violation"))) |>  
  ggplot(aes(x=condition,y=proportion))+
    geom_bar(stat="identity",fill="#e21c70",alpha=0.6)+
    geom_linerange(aes(ymin = CI_lower, ymax = CI_upper))+
    theme_minimal()+
    coord_flip()+
    labs(x=" ",y="\nproportion yes",title="Did [agent] violate the rule?")+
    scale_y_continuous(breaks=c(0,0.25,0.5,0.75,1),limits=c(0,1))+
    theme(
      text = element_text(color = "black"),  # Makes all text black
      axis.text = element_text(color = "black"),  
      axis.title = element_text(color = "black",face="bold"), 
      legend.text = element_text(color = "black"), 
      legend.title = element_text(color = "black"),
      plot.title = element_text(color = "black",face="bold")
  )

p_prop

ggsave(p_prop,file="p_prop.pdf",width=11,height=10,units="cm")
ggsave(p_prop,file="p_prop.png",width=11,height=10,units="cm")
```

```{r}
median_rts <- rules_allstudies |> 
  filter(task=="rules") |> 
  group_by(condition) |> 
  summarize(median = median(rt))

p_rts <- rules_allstudies |> 
  filter(task=="rules") |> 
  mutate(condition=factor(condition,levels=c("full violation","text violation","purpose violation","no violation"))) |> 
  ggplot(aes(x=condition,y=rt))+
  geom_violin(fill="#e21c70",alpha=0.6)+
  geom_point(data=median_rts,aes(x=condition,y=median))+
  theme_minimal()+
  coord_flip()+
  labs(x=" ",y="\nrt",title="reaction times")+
  theme(
      text = element_text(color = "black"),  # Makes all text black
      axis.text = element_text(color = "black"),  
      axis.title = element_text(color = "black",face="bold"), 
      legend.text = element_text(color = "black"), 
      legend.title = element_text(color = "black"),
      plot.title = element_text(color = "black",face="bold")
  )

p_rts

ggsave(p_rts,file="p_rts.pdf",width=11,height=10,units="cm")
ggsave(p_rts,file="p_rts.png",width=11,height=10,units="cm")
```




