---
title: "clean"
format: html
editor: visual
execute:
  warning: false
  message: false
---

# packages

```{r}
library(fuzzyjoin)
library(stringi)
library(reshape2)
library(here)
library(tidyverse)
```

# data

```{r}
raw <- read.csv(here("data","raw_full.csv"))
```

# extract demographics

```{r}
demographics <- raw %>%
  filter(str_detect(response, "age") | str_detect(response, "gender")) %>%
  select(subj_code, response) %>%
  separate(response, into = c("field", "value"), sep = ":", remove = TRUE) %>%
  mutate(
    field = gsub("[^A-Za-z0-9 ]", "", field),  # Keep only letters, numbers, and spaces in 'field'
    value = gsub("[^A-Za-z0-9 ]", "", value)  # Keep only letters, numbers, and spaces in 'value'
  ) %>%
  # Correct handedness fields
  mutate(field = ifelse(value %in% c("righthanded", "lefthanded", "ambidextrous"), "handedness", field)) |> 
  mutate(field = ifelse(field=="age" & value == "","comments",field)) |> 
  mutate(field = ifelse(field=="age"& !grepl("^\\d+\\s*$", value),"comments",field)) 

#check for duplicates
demographics %>%
  group_by(subj_code, field) %>%
  summarise(n = n()) %>%
  filter(n > 1)

#pivot
demographics <- demographics %>%
  pivot_wider(
    names_from = field,  # The 'field' column will become the new column names
    values_from = value  # The 'value' column contains the data for those new columns
  )

#export
write.csv(demographics,"demographics.csv",row.names = F)
```

# selecting variables and responses, initial coding

```{r}
clean <- raw %>% 
  select(subj_code,condition,stimulus,task,rt,key_assignment,trial_index,response) %>% 
  filter(task=="response") %>% 
  mutate(case = ifelse(str_detect(stimulus,"dog"),"restaurant",
                       ifelse(str_detect(stimulus,"shoes"),"shoes",
                              ifelse(str_detect(stimulus,"dormitory"),"noise",
                                     ifelse(str_detect(stimulus,"train station"),"trainstation",
                                            ifelse(str_detect(stimulus,"parliament"),"deer",
                                                   ifelse(str_detect(stimulus,"zero tolerance"),"alcohol",
                                                          ifelse(str_detect(stimulus,"No cars are allowed"),"cars",
                                                                 ifelse(str_detect(stimulus,"headmaster"),"phones","lab")))))))),
         yeskey = ifelse(str_detect(key_assignment,"e for yes"),"e","i"),
         response_num = ifelse(response==yeskey,1,0)) %>% 
  select(-response) %>% 
  rename(response = response_num)

nlevels(factor(clean$subj_code))
```

# stimulus coding

```{r}
codingsheet <- read.csv(here("codebooks","codingsheet.csv"),sep=";") 
```

```{r}
clean <- clean %>% 
  filter(case!="noise") %>% 
  regex_left_join(codingsheet, by = c(stimulus = "question")) %>% 
  select(subj_code,condition,scen,stimulus,trial_index,rule,question,text,purpose,conflict,type,response,rt)
```

# checks

```{r}
#number of participants
nlevels(factor(clean$subj_code))

#trials per participant
clean %>% 
  dplyr::group_by(subj_code) %>% 
  dplyr::summarize(n = n()) |> 
  arrange(n)
```

# exclusions

## noncompleters

```{r}
noncompleters <- clean %>% 
  dplyr::group_by(subj_code) %>% 
  dplyr::summarize(ntrials = n()) %>% 
  filter(ntrials < 96)

clean <- clean %>% dplyr::filter(!subj_code %in% noncompleters$subj_code)

nlevels(factor(clean$subj_code))
```

## invalid responses + rt's under 200 or over 8000 ms

```{r}
clean <- clean %>% 
  filter(rt!="null") %>% # exclude invalid responses
  mutate(rt = as.numeric(rt)) %>% # convert to numeric
  dplyr::filter(rt > 200 & rt < 8000) # exclude very fast and very slow responses

#check distribution of rts after exclusions
summary(clean$rt)

#check new number of participants
nlevels(factor(clean$subj_code))

#check new number of trials per participant
clean %>% 
  dplyr::group_by(subj_code) %>% 
  dplyr::summarize(ntrials = n()) %>%
  summary(ntrials)
```

# condition coding

```{r}
clean <- clean %>% 
  rename(block_order = condition) |> 
  mutate(condition = case_when(
    text==0 & purpose==0 ~ "no violation",
    text==1 & purpose==0 ~ "text violation",
    text==0 & purpose==1 ~ "purpose violation",
    text==1 & purpose==1 ~ "full violation"
  ),
  congruent = ifelse(text==purpose,1,0))
```

# proportion checks and coding

```{r}
#check stimuli: condition 1 should have 4 cases with 10 conflict trials each, then 4 cases with 2 conflict trials each. Condition 2 should be reversed

#code scenario order per participant
scen_order <- clean %>% 
  group_by(subj_code,scen) %>% 
  summarize(m = min(trial_index)) %>% 
  arrange(subj_code,m) %>% 
  mutate(scen_number = rep(1:8,length(nlevels(factor(subj_code)))))

#add info to main dataframe
clean <- left_join(clean,scen_order,by=c("subj_code","scen")) %>% 
        select(-m)

#check whether conditions have been implemented correctly
clean |> 
  group_by(block_order,scen_number) |> 
  summarize(m = mean(conflict)) # looks good - small deviations from true props (0.83 / 0.16) are due to occasional invalid trials

#add prop info to dataframe
clean <- clean |> 
  mutate(conflict_prop = ifelse((block_order==1 & scen_number <= 4) | (block_order==2 & scen_number > 4),"high","low"))

#check
clean |> 
  group_by(block_order,conflict_prop,scen_number) |> 
  summarize(m = mean(conflict))

```

# demographics

```{r}
raw |> 
  filter(str_detect(response,"gender") & str_detect(response,"handed",negate=T) & str_detect(response,"ambidextrous",negate=T)) |> 
  filter(subj_code %in% clean$subj_code) |> 
  select(response) |> 
  group_by(response) |> 
  summarize(n=n()) |> 
  mutate(prop = n/sum(n))

age <- raw |> 
  filter(str_detect(response,"age")) |> 
  filter(subj_code %in% clean$subj_code) |> 
  select(response) 

age$response <- as.numeric(str_extract(age$response, "\\d+"))
  
age <- age |> 
  filter(is.na(response)==F)

mean(age$response)
sd(age$response)

```

# insert demographics

```{r}
clean <- left_join(clean,demographics,by="subj_code")
```

# save

```{r}
write.csv(clean,here("data","clean.csv"),row.names = F)
```
